### ISSUE TITLE
Old urls's to databases not working

### ISSUE THREAD

**Issue by st0at** [gpslab/geoip2#17]
Maxmind changed their policy and user agreements about using their data so old urls like
`https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz`
are not working anymore.
Any suggestions to move to other alternative or are you planning to fix this?

**Comment by peter-gribanov** [comment]
Thanks for your report.

Yes, updating via bundle will stop working. To update the GeoIP database, you will have to use the [`geoipupdate`](https://dev.maxmind.com/geoip/geoipupdate/#For_Free_GeoLite2_Databases) utility.

I will be engaged in renewal of updating database through bundle.

**Comment by neverfan** [comment]
Hi! Easy way to fix it - just replace download link in config. 

Follow this instruction:
1. Sign up account for `GeoIp2` on page: 
https://www.maxmind.com/en/geolite2/signup
2. Login in generate licence key on page: 
https://www.maxmind.com/en/accounts/169195/license-key
Save your licence key.
2. Open download page:
https://www.maxmind.com/en/download_files
Find your needed DB edition `ID` and copy value from first column
![image](https://user-images.githubusercontent.com/2862833/72380833-4ccd5a00-3727-11ea-9c6c-aecd55c086ed.png)
4. Open your config file with `gpslab_geoip` params and replace `url` param by next:
`https://download.maxmind.com/app/geoip_download?edition_id={edition_id}&license_key={license_key}` 

- `ID`  - character ID name from first column on download page
- `license_key` - your saved licence key

**Comment by peter-gribanov** [comment]
@neverfan you must also specify the suffix `&suffix=tar.gz` in the link, otherwise you will get error:
```
Invalid suffix
```
But anyway, thank you very much for this guide.

**Comment by neverfan** [comment]
@peter-gribanov oh, yes, forgot that, I fixed guide.

**Comment by Zizitto** [comment]
> Thanks for your report.
> 
> Yes, updating via bundle will stop working. To update the GeoIP database, you will have to use the [`geoipupdate`](https://dev.maxmind.com/geoip/geoipupdate/#For_Free_GeoLite2_Databases) utility.
> 
> I will be engaged in renewal of updating database through bundle.

we still can use geoip2:update command all you need is add valid URL as first argument, NO?

**Comment by peter-gribanov** [comment]
@Zizitto yes. The `geoip2:update` command is still works.
Need only change the URL in configuration like that:
```yml
gpslab_geoip:
    url: 'https://download.maxmind.com/app/geoip_download?edition_id={edition_id}&license_key={license_key}&suffix=tar.gz'
```

**Comment by ssammut** [comment]
hello ! isn't the compressor unable to extract tar.gz files? For what I've been experiencing the bundle is only extracting the gz leaving us with a tar file in the cache directory

> file var/cache/dev/GeoLite2-City.mmdb 
> var/cache/dev/GeoLite2-City.mmdb: POSIX tar archive (GNU)

**Comment by peter-gribanov** [comment]
@ssammut Yes. Really. MaxMind changed the structure of the archive. I will fix it.

**Comment by peter-gribanov** [comment]
@ssammut can you check now for the `master` branch?

**Comment by ssammut** [comment]
@peter-gribanov that was quick! thanks! tested master and works as expected. mmdb is located in var/cache/env.

thanks again

**Comment by peter-gribanov** [comment]
New [release 1.2.0](https://github.com/gpslab/geoip2/releases/tag/v1.2.0) with fixes for this problem has been published.
Need only change URL in configuration file for correct work a `geoip2:update` command.

**Comment by st0at** [comment]
Thank you people, you are awesome! Everything works like a charm.

**Comment by peter-gribanov** [comment]
In new [release 2.0.0](https://github.com/gpslab/geoip2/releases/tag/v2.0.0) you can simplify configure the download URL by configure only the license kay and edition id.

```yml
gpslab_geoip:
    # Your personal licence key
    license: 'XXXXXXXXXXXXXXXX'

    # Database edition ID
    edition: 'GeoLite2-City'
```
