### ISSUE TITLE
Enable auto-wiring

### ISSUE THREAD

**Issue by henri9813** [gpslab/geoip2#5]
Hello, 

Is it possible to add auto-wiring for the bundle ? 

Thanks :)

**Comment by peter-gribanov** [comment]
@henri9813 Hello. I'm not using Flex. So, can you check this PR #6

**Comment by peter-gribanov** [comment]
Wait this PR https://github.com/symfony/recipes-contrib/pull/717

**Comment by peter-gribanov** [comment]
Now project supported by Symfony Flex and auto write bundle, default config and registr composer script.
