### ISSUE TITLE
Issue with Symfony 4.4 integration - Resource temporarily unavailable

### ISSUE THREAD

**Issue by nudl3s** [gpslab/geoip2#75]
Hi there,

After I have followed the steps and added this bundle to my project, everything was working fine. But when I tried to update the database with the command `("php bin/console geoip2:update")` I have received an error. Do you have any idea what could make this issue. 

> In Filesystem.php line 179:
                                                                                                                                                                                       

>   Failed to remove file "C:\Users\user\AppData\Local\Temp/603784fb9d6e84.54757459_GeoLite2.tar": unlink(C:\Users\user\AppData\Local\Temp/603784fb9d6e84.54757459_GeoL  
>   ite2.tar): Resource temporarily unavailable

Thank You!

**Comment by nudl3s** [comment]
Тhis error occurs when I run the command on localhost (Windows OS). Tested on the server with Linux, everything works as expected.

**Comment by peter-gribanov** [comment]
Does this problem appear on [line 63](https://github.com/gpslab/geoip2/blob/master/src/Downloader/MaxMindDownloader.php#L63) of `MaxMindDownloader` class?

**Comment by nudl3s** [comment]
Nope, it appears to be on [https://github.com/gpslab/geoip2/blob/db9a7314479c3b9b49f5bfdb0e3b2719a2eeded1/src/Downloader/MaxMindDownloader.php#L111](url) same class

**Comment by peter-gribanov** [comment]
@nudl3s can you check this fix #76

**Comment by nudl3s** [comment]
Nice, working fine now

**Comment by peter-gribanov** [comment]
Fix released in [v2.0.7](https://github.com/gpslab/geoip2/releases/tag/v2.0.7).
