### ISSUE TITLE
GeoIP2-php 3.0.0 available

### ISSUE THREAD

**Issue by Huluti** [gpslab/geoip2#92]
Hello! Just for info, GeoIP2-php 3.0.0 available

https://github.com/maxmind/GeoIP2-php/releases/tag/v3.0.0

**Comment by peter-gribanov** [comment]
GeoIP2-php 3. support added in [Release 2.1.1](https://github.com/gpslab/geoip2/releases/tag/v2.1.1)

**Comment by Huluti** [comment]
Thanks a lot, will test it!

**Comment by Huluti** [comment]
works perfectly!
